Fixing node creationg flow
gardener/machine-controller-manager-provider-yandex pull request #4
Opened 2021-07-05 21:38 UTC by preved911

**What this PR does / why we need it**:
Because right now flow not working: new machine object does not create VM and not join it to cluster.

**Which issue(s) this PR fixes**:
Fixes #3

2021-07-05 21:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/machine-controller-manager-provider-yandex?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/machine-controller-manager-provider-yandex?pullRequest=4) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/machine-controller-manager-provider-yandex?pullRequest=4) it.</sub>

2021-07-29 15:02 UTC, hardikdr commented
cc @zuzzas @AxiomSamarth

2021-07-29 16:30 UTC, AxiomSamarth requested changes

2021-07-29 16:30 UTC, AxiomSamarth commented on go.mod
> +	github.com/gardener/machine-controller-manager => github.com/gardener/machine-controller-manager v0.39.0
MCM v0.39.0 is being vendored under the `require` section. I do not see a reason to replace it with the same version under the `replace` section of this `go.mod`. You can remove this line.

2021-07-29 16:33 UTC, AxiomSamarth commented
Thanks for this PR. Also, I would recommend you to consider to add logic to handle this [issue](https://github.com/gardener/machine-controller-manager/issues/599#). I have already raised a [PR](https://github.com/gardener/machine-controller-manager-provider-yandex/pull/2) for it.

2021-07-29 22:32 UTC, preved911 commented
> I have already raised a [PR](https://github.com/gardener/machine-controller-manager-provider-yandex/pull/2) for it.

So, can somebody merge it? I would rebase my PR from new master head after this.

2021-07-30 03:28 UTC, prashanth26 commented
@zuzzas - Is the maintainer here. Can you please take a look?

2021-07-30 06:04 UTC, PavelPavlov46 commented
Yea, I contacted Andrey (@zuzzas) on 19th Jul over slack but didn't get a response. Let me try also over email.

2021-08-26 06:24 UTC, preved911 commented
> Yea, I contacted Andrey (@zuzzas) on 19th Jul over slack but didn't get a response. Let me try also over email or some other channel.

Andrey (@zuzzas) didn't answer? Can we continue without his answer?

2021-08-26 08:50 UTC, hardikdr commented
I think we need to add more folks here to the Yandex-maintainer list for others to be able to review and merge it. 
@msohn

2021-08-26 12:16 UTC, msohn commented
Looking at the [contributors of this repo](https://github.com/gardener/machine-controller-manager-provider-yandex/graphs/contributors) it seems Prashanth (@prashanth26) would be the natural candidate to be added as a maintainer.

WDYT ?

2021-08-26 13:21 UTC, hardikdr commented
Sounds good to me, I guess @prashanth26 @AxiomSamarth are in the best position to suggest though.

2021-08-27 08:02 UTC, msohn commented
After discussion with  @prashanth26 I added @AxiomSamarth to the @gardener/yandex-provider-maintainers group in order to unblock this PR review.

2021-08-27 11:40 UTC, AxiomSamarth approved these changes

2021-08-27 11:40 UTC, AxiomSamarth commented
/lgtm

2021-08-27 11:41 UTC, merged